AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This workload template deploys a single instance of selected Pyramid processes
  against a pre-existing deployment.
  You will be billed for the AWS resources used if you create a stack from this template. 
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Instance configuration
        Parameters:
          - BaseStackName
          - Subnet
          - InstanceType
          - PyramidProcess
          - AssignPublicIP
    ParameterLabels:
      BaseStackName:
        default: Stack Name of Central instance stack
      Subnet:
        default: Subnet for Pyramid instance
      InstanceType:
        default: Instance type
      AssignPublicIP:
        default: Assign public IP and domain name
      PyramidProcess:
        default: Pyramid process(es) for instance
Parameters:
  Subnet:
    Description: Subnet for instance within VPC of the original single instance Stack
    Type: 'AWS::EC2::Subnet::Id'
  BaseStackName:
    Description: StackName of a Central instance deployment being added onto.
    Type: String
    MinLength: '1'
    AllowedPattern: '[-_a-zA-Z0-9]*'
    ConstraintDescription: Required
  InstanceType:
    Description: >-
      Amazon EC2 instance type for the Pyramid instances. Has to be available
      for the deployment region.
    Type: String
    AllowedValues:
      - t3.2xlarge
      - t3a.2xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.12xlarge
      - c5.18xlarge
      - c5.24xlarge
      - c5a.2xlarge
      - c5a.4xlarge
      - c5a.8xlarge
      - c5a.12xlarge
      - c5a.16xlarge
      - c5a.24xlarge
      - c5ad.2xlarge
      - c5ad.4xlarge
      - c5ad.8xlarge
      - c5ad.12xlarge
      - c5ad.16xlarge
      - c5ad.24xlarge
      - c5d.2xlarge
      - c5d.4xlarge
      - c5d.9xlarge
      - c5d.12xlarge
      - c5d.18xlarge
      - c5d.24xlarge
      - c5n.2xlarge
      - c5n.4xlarge
      - c5n.9xlarge
      - c5n.18xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - m5a.2xlarge
      - m5a.4xlarge
      - m5a.8xlarge
      - m5a.12xlarge
      - m5a.16xlarge
      - m5a.24xlarge
      - m5ad.2xlarge
      - m5ad.4xlarge
      - m5ad.8xlarge
      - m5ad.12xlarge
      - m5ad.16xlarge
      - m5ad.24xlarge
      - m5d.2xlarge
      - m5d.4xlarge
      - m5d.8xlarge
      - m5d.12xlarge
      - m5d.16xlarge
      - m5d.24xlarge
      - m5dn.2xlarge
      - m5dn.4xlarge
      - m5dn.8xlarge
      - m5dn.12xlarge
      - m5dn.16xlarge
      - m5dn.24xlarge
      - m5n.2xlarge
      - m5n.4xlarge
      - m5n.8xlarge
      - m5n.12xlarge
      - m5n.16xlarge
      - m5n.24xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - r5.12xlarge
      - r5.16xlarge
      - r5.24xlarge
      - r5a.2xlarge
      - r5a.4xlarge
      - r5a.8xlarge
      - r5a.12xlarge
      - r5a.16xlarge
      - r5a.24xlarge
      - r5ad.2xlarge
      - r5ad.4xlarge
      - r5ad.8xlarge
      - r5ad.12xlarge
      - r5ad.16xlarge
      - r5ad.24xlarge
      - r5d.2xlarge
      - r5d.4xlarge
      - r5d.8xlarge
      - r5d.12xlarge
      - r5d.16xlarge
      - r5d.24xlarge
      - r5dn.2xlarge
      - r5dn.4xlarge
      - r5dn.8xlarge
      - r5dn.12xlarge
      - r5dn.16xlarge
      - r5dn.24xlarge
      - r5n.2xlarge
      - r5n.4xlarge
      - r5n.8xlarge
      - r5n.12xlarge
      - r5n.16xlarge
      - r5n.24xlarge
      - t3.2xlarge
      - t3a.2xlarge
      - x1.16xlarge
      - x1.32xlarge
      - x1e.2xlarge
      - x1e.4xlarge
      - x1e.8xlarge
      - x1e.16xlarge
      - x1e.32xlarge
    Default: c5.2xlarge
    ConstraintDescription: Must contain valid instance type.
  AssignPublicIP:
    Description: >-
      Assign public IP address and domain.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    ConstraintDescription: Required
  PyramidProcess:
    Description: >-
      For unattended installation.
    Type: String
    AllowedValues:
      - Everything
      - Router
      - WebServer
      - WebServerAndRouter
      - RuntimeEngine
      - TaskEngine
      - RuntimeEngineAndTaskEngine
      - RuntimeEngineAndAI
      - TaskEngineAndAI
      - RuntimeAndTaskEngineAndAI
      - EverythingExceptInMemoryDB
      - AIServer
      - InMemoryDB
      - Nothing
    Default: Everything
Mappings:

# 2020.24.054 AWS version

  AWSAMIRegionMap:
    us-east-1:
      '64': ami-01daa081362bbcd8f
    us-gov-west-1:
      '64': ami-03e70e3d4a569d582
    us-gov-east-1:
      '64': ami-06965849c7f9cc92e
    us-east-2:
      '64': ami-065a8c9d489b61384
    us-west-1:
      '64': ami-04e2b84296903d06c
    us-west-2:
      '64': ami-02279b2c4f7361405
    ca-central-1:
      '64': ami-08004e340be26e624
    eu-central-1:
      '64': ami-0c021d3b45e298ee5
    eu-west-1:
      '64': ami-07c7200d1881c8824
    eu-west-2:
      '64': ami-0479bba44666a6ffd
    eu-west-3:
      '64': ami-08d50ac7da274f44d
    ap-southeast-1:
      '64': ami-0158239af3dff6942
    ap-southeast-2:
      '64': ami-08f4d79d8af626021
    ap-south-1:
      '64': ami-019569227c9569ced
    ap-northeast-1:
      '64': ami-0955c4e6753d1e733
    ap-northeast-2:
      '64': ami-05917e51c2226bc9d
    sa-east-1:
      '64': ami-0f2e5b1bd37243196
    eu-north-1:
      '64': ami-0a509e20b5fcb750f
    me-south-1:
      '64': ami-025f1c20cb62708b9
    af-south-1:
      '64': ami-069bbb56d52dbf0d7
    eu-south-1:
      '64': ami-015a7108facad1be3

Conditions:
  WebAccess: !Or
    - !Equals
      - !Ref PyramidProcess
      - 'Everything'
    - !Equals
      - !Ref PyramidProcess
      - 'WebServerAndRouter'
    - !Equals
      - !Ref PyramidProcess
      - 'WebServer'
  PublicIP: !And
    - !Condition WebAccess
    - !Equals
      - !Ref AssignPublicIP
      - 'true'

Resources:
  LaunchInstance:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://pyramid-cloudformation.s3.amazonaws.com/marketplace/2020-24/pyramid-single-instance.yaml
      Parameters:
        BaseStackName: !Ref BaseStackName
        AMIID: !FindInMap 
          - AWSAMIRegionMap
          - !Ref 'AWS::Region'
          - '64'
        PyramidProcess: !Ref PyramidProcess
        InstancePurpose: !Ref PyramidProcess
        InstanceType: !Ref InstanceType

        Subnet: !Ref Subnet
        WorkloadSecurityGroups: !Join
          - ','
          - - !Sub '{{resolve:ssm:/Pyramid/${BaseStackName}/PyramidProcessesSecurityGroup:1}}'
            - !Sub '{{resolve:ssm:/Pyramid/${BaseStackName}/MountTargetSecurityGroup:1}}'
            - !If
              - WebAccess
              - !Sub '{{resolve:ssm:/Pyramid/${BaseStackName}/WebAccessSecurityGroup:1}}'
              - !Ref 'AWS::NoValue'
        InstallProxy: !If
          - WebAccess
          - true
          - false
        AssignPublicIP: !If
          - WebAccess
          - !Ref AssignPublicIP
          - false

        RepositoryType: currentremote

Outputs:
  PyramidPublicURL:
    Value: !If
      - PublicIP
      - !Join
        - ''
        - - 'http://'
          - !GetAtt LaunchInstance.Outputs.PublicDNSName
      - 'No public URL'
    Description: Pyramid Public URL
  PublicDNSName:
    Value: !GetAtt LaunchInstance.Outputs.PublicDNSName
    Description: Instance Public DNS name
  PrivateDNSName:
    Value: !GetAtt LaunchInstance.Outputs.PrivateDNSName
    Description: Instance Private DNS name
