AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS Aurora Postgres, Do Not Remove Apache License Version 2.0 (qs-1pj6s43e3) July,23,2019"
Metadata:
  LICENSE: Apache License Version 2.0
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - VPCID
      # - Subnets
      - SubnetIds
      - DBAccessCIDR
      - CustomDBSecurityGroup
    - Label:
        default: Database configuration
      Parameters:
      - ClusterName
      - DBAutoMinorVersionUpgrade
      - DBBackupRetentionPeriod
      - DBEngineVersion
      - DBEngineMode
      - DBInstanceClass
      - DBPort
      - DBMultiAZ
      - DBAllocatedStorageEncrypted
      - DBMasterUsername
      - DBMasterUserPassword
    ParameterLabels:
      ClusterName:
        default: Aurora cluster name
      DBEngineVersion:
        default: Database Engine Version
      DBEngineMode:
        default: Aurora provisioned or Serverless deployment
      DBAllocatedStorageEncrypted:
        default: Database encryption enabled
      DBAutoMinorVersionUpgrade:
        default: Database auto minor version upgrade
      DBBackupRetentionPeriod:
        default: Database backup retention period
      DBInstanceClass:
        default: Database instance class for provisioned cluster
      DBMasterUsername:
        default: Database master username
      DBMasterUserPassword:
        default: Database master password
      DBPort:
        default: Database port
      DBAccessCIDR:
        default: CIDR that can access the cluster
      DBMultiAZ:
        default: Multi-AZ deployment
      # Subnets:
      #   default: Subnets in VPC to deploy instances
      SubnetIds:
        default: Subnet Ids in VPC to deploy instances. String of comma separated Ids used when this template is nested.
      VPCID:
        default: VPC ID
      CustomDBSecurityGroup:
        default: Pre-defined security group ID for cluster access

Mappings:
  DBFamilyMap:
    "9.6.9":
      "family": "aurora-postgresql9.6"
    "9.6.11":
      "family": "aurora-postgresql9.6"
    "9.6.12":
      "family": "aurora-postgresql9.6"
    "10.5":
      "family": "aurora-postgresql10"
    "10.6":
      "family": "aurora-postgresql10"
    "10.7":
      "family": "aurora-postgresql10"
    "11.4":
      "family": "aurora-postgresql11"
    "11.6":
      "family": "aurora-postgresql11"
    "11.7":
      "family": "aurora-postgresql11"
Parameters:
  DBAllocatedStorageEncrypted:
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Whether or not to encrypt the database.
    Type: String
  DBAutoMinorVersionUpgrade: 
    AllowedValues: 
      - "true"
      - "false"
    Default: "true"
    Description: "Select true to set up auto minor version upgrade."
    Type: String
  DBBackupRetentionPeriod: 
    Default: "35"
    Description: "The number of days for which automatic database snapshots are retained."
    Type: String
  DBEngineVersion:
    Description: Select Database Engine Version
    Type: String
    Default: 10.7
    AllowedValues:
      - 9.6.9
      - 9.6.11
      - 9.6.12
      - 10.5
      - 10.6
      - 10.7
      - 11.4
      - 11.6
      - 11.7
  DBEngineMode:
    Description: Database Engine Mode
    Type: String
    Default: serverless
    AllowedValues:
      - serverless
      - provisioned
  DBInstanceClass:
    AllowedValues:
      - db.r5.large
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.12xlarge
      - db.r5.24xlarge
      - db.r4.large
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
    ConstraintDescription: "If not serverless, select a valid database instance type."
    Default: db.r5.large
    Description: "The name of the compute and memory capacity class of the database instance."
    Type: String
  DBAccessCIDR:
    AllowedPattern: "(^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$)?"
    ConstraintDescription: "CIDR block parameter must be in the form x.x.x.x/x"
    Description: "Allowed CIDR block for external access (use VPC CIDR)."
    Type: String
    Default: ''
  DBMasterUserPassword:
    AllowedPattern: >-
      ^(?=^.{8,255}$)(?=.*[a-z])(?=.*[A-Z])(?=.*\d)((?=.*[^A-Za-z0-9])(?!.*[@/"'])).*$
    ConstraintDescription: >-
      Min 8 chars. Must include 1 uppercase, 1 lowercase, 1 number, 1 (non / @ " ') symbol
    Description: "The database admin account password."
    MaxLength: "64"
    MinLength: "8"
    NoEcho: "True"
    Type: String
  DBMasterUsername: 
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "Must begin with a letter and contain only alphanumeric characters."
    Default: pgadmin
    Description: "The database admin account username."
    MaxLength: "16"
    MinLength: "1"
    Type: String
  DBPort:
    Default: 5432
    Description: "The port the instance will listen for connections on."
    Type: Number
    ConstraintDescription: 'Must be in the range [1115-65535].'
    MinValue: 1150
    MaxValue: 65535
  DBMultiAZ: 
    AllowedValues: 
      - true
      - false
    Default: true
    Description: "Specifies if the database instance is a multiple Availability Zone deployment."
    Type: String
  ClusterName: 
    AllowedPattern: "[-_a-zA-Z0-9]*"
    Description: "Name of the Amazon Aurora cluster. Will default if not entered"
    MaxLength: "64"
    Default: ''
    Type: String
  CustomDBSecurityGroup:
    Description: "ID of the security group (e.g., sg-0234se). An RDSSecurityGroup will be created if this parameter is left empty."
    Type: String
    Default: ''
  # Subnets:
  #   Description: Subnets to deploy instances into
  #   Type: 'List<AWS::EC2::Subnet::Id>'
  #   Default: ''
  SubnetIds:
    Description: Subnet Ids to deploy instances into.
    Type: CommaDelimitedList
  VPCID: 
    Description: "ID of the VPC you are deploying Aurora into (e.g., vpc-0343606e)."
    Type: 'AWS::EC2::VPC::Id'

Rules:
  SubnetsInVPC:
    Assertions:
      - Assert:
          'Fn::EachMemberIn':
            - 'Fn::ValueOfAll':
                - 'AWS::EC2::Subnet::Id'
                - VpcId
            - 'Fn::RefAll': 'AWS::EC2::VPC::Id'
        AssertDescription: All subnets must in the same VPC
Conditions: 
  CreateSecurityGroup:
    !Equals
      - !Ref CustomDBSecurityGroup
      - ''
  CreateCIDRIngress: !And
    - !Not
      - !Equals
        - !Ref DBAccessCIDR
        - ''
    - !Condition CreateSecurityGroup
  IsProvisioned: !Equals
    - !Ref DBEngineMode
    - 'provisioned'
  IsDBMultiAZ: !And
    - !Equals
      - !Ref DBMultiAZ
      - 'true'
    - !Condition IsProvisioned
  UseDatabaseEncryption: !Equals
    - !Ref DBAllocatedStorageEncrypted
    - 'true'

Resources:

  # this template has a retain policy in the callers
  # do not retain here, to allow deletion
  EncryptionKey:
    Type: AWS::KMS::Key
    Condition: UseDatabaseEncryption
    # DeletionPolicy: Retain
    # UpdateReplacePolicy: Retain
    Properties:
      KeyPolicy:
        Version: 2012-10-17
        Id: !Ref "AWS::StackName"
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action: 'kms:*'
            Resource: '*'
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

  EncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Condition: UseDatabaseEncryption
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}"
      TargetKeyId: !Ref EncryptionKey

  DBParamGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Description: !Join [ "- ", [ "Aurora PostgreSQL for Cloudformation Stack ", !Ref 'AWS::StackName' ] ]
      Family: !FindInMap [DBFamilyMap, !Ref DBEngineVersion, "family"]
      Parameters:
        log_rotation_age: '1440'
        log_rotation_size: '102400'
  RDSDBClusterParameterGroup:
    Type: AWS::RDS::DBClusterParameterGroup
    Properties:
      Description: !Join [ "- ", [ "Aurora PostgreSQL for  Cloudformation Stack ", !Ref 'AWS::StackName' ] ]
      Family: !FindInMap [DBFamilyMap, !Ref DBEngineVersion, "family"]
      Parameters:
        rds.force_ssl: 0

  AuroraDBCluster:
    Type: "AWS::RDS::DBCluster"
    Properties:
      BackupRetentionPeriod: !Ref DBBackupRetentionPeriod
      DBClusterParameterGroupName: !Ref RDSDBClusterParameterGroup
      DBSubnetGroupName: !Ref AuroraDBSubnetGroup
      DBClusterIdentifier: !Ref ClusterName
      Engine: aurora-postgresql
      EngineVersion: !Ref DBEngineVersion
      EngineMode: !Ref DBEngineMode
      KmsKeyId: !If [UseDatabaseEncryption, !GetAtt EncryptionKey.Arn, !Ref 'AWS::NoValue']
      MasterUserPassword: !Ref DBMasterUserPassword
      MasterUsername: !Ref DBMasterUsername
      Port: !Ref DBPort
      StorageEncrypted: !If [UseDatabaseEncryption, !Ref DBAllocatedStorageEncrypted, !Ref 'AWS::NoValue']
      Tags: 
        - 
          Key: Name
          Value: !Sub AuroraDB-${AWS::StackName}
      VpcSecurityGroupIds: 
        !If
          - CreateSecurityGroup
          - [!Ref RDSSecurityGroup]
          - [!Ref CustomDBSecurityGroup]
    # UpdateReplacePolicy: Snapshot
    # DeletionPolicy: Retain

  AuroraDB1:
    Type: "AWS::RDS::DBInstance"
    Condition: IsProvisioned
    Properties:
      AutoMinorVersionUpgrade: !Ref DBAutoMinorVersionUpgrade
      DBClusterIdentifier: !Ref AuroraDBCluster
      DBInstanceClass: !Ref DBInstanceClass
      Engine: aurora-postgresql
      EngineVersion: !Ref DBEngineVersion
      DBParameterGroupName: !Ref DBParamGroup
      PubliclyAccessible: false
      Tags:
        -
          Key: Name
          Value: !Sub AuroraDB-${AWS::StackName}

  AuroraDB2:
    Type: "AWS::RDS::DBInstance"
    Condition: IsDBMultiAZ
    Properties:
      AutoMinorVersionUpgrade: !Ref DBAutoMinorVersionUpgrade
      DBClusterIdentifier: !Ref AuroraDBCluster
      DBInstanceClass: !Ref DBInstanceClass
      Engine: aurora-postgresql
      EngineVersion: !Ref DBEngineVersion
      DBParameterGroupName: !Ref DBParamGroup
      PubliclyAccessible: false
      Tags:
        -
          Key: Name
          Value: !Sub AuroraDB-${AWS::StackName}

  AuroraDBSubnetGroup: 
    Type: "AWS::RDS::DBSubnetGroup"
    Properties: 
      DBSubnetGroupDescription: "Subnets available for the Amazon Aurora database instance"
      SubnetIds: !Ref SubnetIds

  RDSSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Condition: CreateSecurityGroup
    Properties: 
      GroupDescription: "Allow access to database port" 
      SecurityGroupEgress: 
        - 
          CidrIp: 0.0.0.0/0
          IpProtocol: '-1'
          FromPort: -1
          ToPort: -1
      VpcId: !Ref VPCID
      Tags:
      - Key: Name
        Value: !Sub RDSSecurityGroup-${AWS::StackName}

  RDSSecurityGroupIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Condition: CreateSecurityGroup
    Properties:
      GroupId: !GetAtt 'RDSSecurityGroup.GroupId'
      IpProtocol: '-1'
      SourceSecurityGroupId: !Ref RDSSecurityGroup
      Description: 'Self Reference'

  # CidrOfVpc:
  #   Type: Custom::CidrOfVpc
  #   Properties:
  #     ServiceToken: !ImportValue CidrOfVpc
  #     VpcId: !Ref VPCID
  #     Region: !Ref 'AWS::Region'

  # VpcSecurityGroupIngress:
  #   Type: 'AWS::EC2::SecurityGroupIngress'
  #   Properties:
  #     GroupId: !GetAtt 'RDSSecurityGroup.GroupId'
  #     IpProtocol: tcp
  #     FromPort: !Ref DBPort
  #     ToPort: !Ref DBPort
  #     CidrIp: !GetAtt CidrOfVpc.CidrBlock 
  #     Description: 'VPC CIDR'

  CIDRIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    Condition: CreateCIDRIngress
    Properties:
      GroupId: !GetAtt 'RDSSecurityGroup.GroupId'
      CidrIp: !Ref DBAccessCIDR 
      IpProtocol: tcp
      FromPort: !Ref DBPort
      ToPort: !Ref DBPort

Outputs:
  DBMasterUsername:
    Description: "Amazon Aurora database master username"
    Value: !Ref DBMasterUsername
  RDSEndPointAddress: 
    Description: "Amazon Aurora endpoint"
    Value: !Sub ${AuroraDBCluster.Endpoint.Address}
  RDSEndPointPort: 
    Description: "Amazon Aurora port"
    Value: !Sub ${AuroraDBCluster.Endpoint.Port}
  RDSEndPoint: 
    Description: "Full Amazon Aurora endpoint"
    Value: !Sub ${AuroraDBCluster.Endpoint.Address}:${AuroraDBCluster.Endpoint.Port}
  RDSSecurityGroup: 
    Description: Security group for access to cluster
    Value: !If
      - CreateSecurityGroup
      - !Ref RDSSecurityGroup
      - !Ref CustomDBSecurityGroup
  RDSEncryptionKey:
    Description: The alias of the encryption key created for RDS
    Value: !If
      - UseDatabaseEncryption
      - !Ref EncryptionKeyAlias
      - 'Not created'
