AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This workload template deploys a single instance of selected Pyramid processes
  against a pre-existing deployment.
  You will be billed for the AWS resources used if you create a stack from this template. 
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Instance configuration
        Parameters:
          - BaseStackName
          - Subnet
          - InstanceType
          - PyramidProcess
          - AssignPublicIP
    ParameterLabels:
      BaseStackName:
        default: Stack Name of Central instance stack
      Subnet:
        default: Subnet for Pyramid instance
      InstanceType:
        default: Instance type
      AssignPublicIP:
        default: Assign public IP and domain name
      PyramidProcess:
        default: Pyramid process(es) for instance
Parameters:
  Subnet:
    Description: Subnet for instance within VPC of the original single instance Stack
    Type: 'AWS::EC2::Subnet::Id'
  BaseStackName:
    Description: StackName of a Central instance deployment being added onto.
    Type: String
    MinLength: '1'
    AllowedPattern: '[-_a-zA-Z0-9]*'
    ConstraintDescription: Required
  InstanceType:
    Description: >-
      Amazon EC2 instance type for the Pyramid instances. Has to be available
      for the deployment region.
    Type: String
    AllowedValues:
      - t3.2xlarge
      - t3a.2xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.9xlarge
      - c5.12xlarge
      - c5.18xlarge
      - c5.24xlarge
      - c5a.2xlarge
      - c5a.4xlarge
      - c5a.8xlarge
      - c5a.12xlarge
      - c5a.16xlarge
      - c5a.24xlarge
      - c5ad.2xlarge
      - c5ad.4xlarge
      - c5ad.8xlarge
      - c5ad.12xlarge
      - c5ad.16xlarge
      - c5ad.24xlarge
      - c5d.2xlarge
      - c5d.4xlarge
      - c5d.9xlarge
      - c5d.12xlarge
      - c5d.18xlarge
      - c5d.24xlarge
      - c5n.2xlarge
      - c5n.4xlarge
      - c5n.9xlarge
      - c5n.18xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - m5a.2xlarge
      - m5a.4xlarge
      - m5a.8xlarge
      - m5a.12xlarge
      - m5a.16xlarge
      - m5a.24xlarge
      - m5ad.2xlarge
      - m5ad.4xlarge
      - m5ad.8xlarge
      - m5ad.12xlarge
      - m5ad.16xlarge
      - m5ad.24xlarge
      - m5d.2xlarge
      - m5d.4xlarge
      - m5d.8xlarge
      - m5d.12xlarge
      - m5d.16xlarge
      - m5d.24xlarge
      - m5dn.2xlarge
      - m5dn.4xlarge
      - m5dn.8xlarge
      - m5dn.12xlarge
      - m5dn.16xlarge
      - m5dn.24xlarge
      - m5n.2xlarge
      - m5n.4xlarge
      - m5n.8xlarge
      - m5n.12xlarge
      - m5n.16xlarge
      - m5n.24xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - r5.12xlarge
      - r5.16xlarge
      - r5.24xlarge
      - r5a.2xlarge
      - r5a.4xlarge
      - r5a.8xlarge
      - r5a.12xlarge
      - r5a.16xlarge
      - r5a.24xlarge
      - r5ad.2xlarge
      - r5ad.4xlarge
      - r5ad.8xlarge
      - r5ad.12xlarge
      - r5ad.16xlarge
      - r5ad.24xlarge
      - r5d.2xlarge
      - r5d.4xlarge
      - r5d.8xlarge
      - r5d.12xlarge
      - r5d.16xlarge
      - r5d.24xlarge
      - r5dn.2xlarge
      - r5dn.4xlarge
      - r5dn.8xlarge
      - r5dn.12xlarge
      - r5dn.16xlarge
      - r5dn.24xlarge
      - r5n.2xlarge
      - r5n.4xlarge
      - r5n.8xlarge
      - r5n.12xlarge
      - r5n.16xlarge
      - r5n.24xlarge
      - t3.2xlarge
      - t3a.2xlarge
      - x1.16xlarge
      - x1.32xlarge
      - x1e.2xlarge
      - x1e.4xlarge
      - x1e.8xlarge
      - x1e.16xlarge
      - x1e.32xlarge
    Default: c5.2xlarge
    ConstraintDescription: Must contain valid instance type.
  AssignPublicIP:
    Description: >-
      Assign public IP address and domain.
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
    ConstraintDescription: Required
  PyramidProcess:
    Description: >-
      For unattended installation.
    Type: String
    AllowedValues:
      - Everything
      - Router
      - WebServer
      - WebServerAndRouter
      - RuntimeEngine
      - TaskEngine
      - RuntimeEngineAndTaskEngine
      - RuntimeEngineAndAI
      - TaskEngineAndAI
      - RuntimeAndTaskEngineAndAI
      - EverythingExceptInMemoryDB
      - AIServer
      - InMemoryDB
      - Nothing
    Default: Everything
Mappings:
# 2020.17.033 AWS version
  AWSAMIRegionMap:
    us-east-1:
      '64': ami-0bca171b7f8d777f0
    us-gov-east-1:
      '64': ami-084d631320467a816
    us-gov-west-1:
      '64': ami-0c7b7af0ce61a5c4e
    us-east-2:
      '64': ami-09a6e3202e6055c2b
    us-west-1:
      '64': ami-0db85e425259e7acf
    us-west-2:
      '64': ami-0eedf2de0c8a490f5
    ca-central-1:
      '64': ami-095694bbb5c882bab
    eu-west-1:
      '64': ami-084519098ac357b29
    eu-west-2:
      '64': ami-017c76427bf17b5b3
    eu-west-3:
      '64': ami-09d0a296ad41768be
    eu-central-1:
      '64': ami-0647e92f7186538b8
    eu-north-1:
      '64': ami-0e80903451f0ad340
    eu-south-1:
      '64': ami-09e8a32ec5a4e0de8
    ap-northeast-1:
      '64': ami-00a45dfe1c2f470f2
    ap-northeast-2:
      '64': ami-0a027c04ec2ebaf39
    ap-southeast-1:
      '64': ami-04be10fa0ae074680
    ap-southeast-2:
      '64': ami-08ac04d72e1a67f56
    sa-east-1:
      '64': ami-078d1af001273c634
    ap-south-1:
      '64': ami-04e097147ad76c6c0
    me-south-1:
      '64': ami-06679292d99028825
    af-south-1:
      '64': ami-0b26f6f6594e6ac06

Conditions:
  WebAccess: !Or
    - !Equals
      - !Ref PyramidProcess
      - 'Everything'
    - !Equals
      - !Ref PyramidProcess
      - 'WebServerAndRouter'
    - !Equals
      - !Ref PyramidProcess
      - 'WebServer'
  PublicIP: !And
    - !Condition WebAccess
    - !Equals
      - !Ref AssignPublicIP
      - 'true'

Resources:
  LaunchInstance:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://pyramid-cloudformation.s3.amazonaws.com/marketplace/2020-17/pyramid-single-instance.yaml
      Parameters:
        BaseStackName: !Ref BaseStackName
        AMIID: !FindInMap 
          - AWSAMIRegionMap
          - !Ref 'AWS::Region'
          - '64'
        PyramidProcess: !Ref PyramidProcess
        InstancePurpose: !Ref PyramidProcess
        InstanceType: !Ref InstanceType

        Subnet: !Ref Subnet
        WorkloadSecurityGroups: !Join
          - ','
          - - !Sub '{{resolve:ssm:/Pyramid/${BaseStackName}/PyramidProcessesSecurityGroup:1}}'
            - !Sub '{{resolve:ssm:/Pyramid/${BaseStackName}/MountTargetSecurityGroup:1}}'
            - !If
              - WebAccess
              - !Sub '{{resolve:ssm:/Pyramid/${BaseStackName}/WebAccessSecurityGroup:1}}'
              - !Ref 'AWS::NoValue'
        InstallProxy: !If
          - WebAccess
          - true
          - false
        AssignPublicIP: !If
          - WebAccess
          - !Ref AssignPublicIP
          - false

        RepositoryType: currentremote

Outputs:
  PyramidPublicURL:
    Value: !If
      - PublicIP
      - !Join
        - ''
        - - 'http://'
          - !GetAtt LaunchInstance.Outputs.PublicDNSName
      - 'No public URL'
    Description: Pyramid Public URL
  PublicDNSName:
    Value: !GetAtt LaunchInstance.Outputs.PublicDNSName
    Description: Instance Public DNS name
  PrivateDNSName:
    Value: !GetAtt LaunchInstance.Outputs.PrivateDNSName
    Description: Instance Private DNS name
