AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This workload template deploys a single instance of selected Pyramid processes
  against a pre-existing deployment.
  You will be billed for the AWS resources used if you create a stack from this template. 
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Instance configuration
        Parameters:
          - BaseStackName
          - Subnet
          - InstanceType
          - PyramidProcess
    ParameterLabels:
      BaseStackName:
        default: Stack Name of base single instance stack
      Subnet:
        default: Subnet for Pyramid instance
      InstanceType:
        default: Instance type
      PyramidProcess:
        default: Pyramid process(es) for instance
Parameters:
  Subnet:
    Description: Subnet for instance within VPC of the original single instance Stack
    Type: 'AWS::EC2::Subnet::Id'
  BaseStackName:
    Description: StackName of the original single instance deployment being added onto.
    Type: String
    MinLength: '1'
    ConstraintDescription: Required
  InstanceType:
    Description: >-
      Amazon EC2 instance type for the Pyramid instances. Has to be available
      for the deployment region.
    Type: String
    AllowedValues:
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - m5.12xlarge
      - m5a.xlarge
      - m5a.2xlarge
      - m5a.4xlarge
      - m5a.8xlarge
      - m5a.12xlarge
      - m5n.xlarge
      - m5n.2xlarge
      - m5n.4xlarge
      - m5n.8xlarge
      - m5n.12xlarge
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.8xlarge
      - c5.12xlarge
      - c5a.xlarge
      - c5a.2xlarge
      - c5a.4xlarge
      - c5a.8xlarge
      - c5a.12xlarge
      - c5n.xlarge
      - c5n.2xlarge
      - c5n.4xlarge
      - c5n.8xlarge
      - c5n.12xlarge
    Default: c5.2xlarge
    ConstraintDescription: Must contain valid instance type.
  PyramidProcess:
    Description: >-
      For unattended installation.
    Type: String
    AllowedValues:
      - Everything
      - Router
      - WebServer
      - WebServerAndRouter
      - RuntimeEngine
      - TaskEngine
      - RuntimeEngineAndTaskEngine
      - RuntimeEngineAndAI
      - TaskEngineAndAI
      - RuntimeAndTaskEngineAndAI
      - AIServer
      - InMemoryDB
      - Nothing
    Default: Everything
Mappings:
  AWSAMIRegionMap:
    us-east-1:
      # 2020.13.100
      # '64': ami-029d57f27fac5962a
      # 2020.14.035
      '64': ami-04708aafb77fcf566
    us-east-2:
      '64': XXX
    us-west-1:
      '64': XXX
    us-west-2:
      '64': XXX
    ca-central-1:
      '64': XXX
    eu-central-1:
      '64': XXX
    eu-west-1:
      '64': XXX
    eu-west-2:
      '64': XXX
    eu-west-3:
      '64': XXX
    eu-north-1:
      '64': XXX
    ap-southeast-1:
      '64': XXX
    ap-southeast-2:
      '64': XXX
    ap-south-1:
      '64': XXX
    ap-northeast-1:
      '64': XXX
    ap-northeast-2:
      '64': XXX
    sa-east-1:
      '64': XXX
    us-gov-east-1:
      '64': XXX
    us-gov-west-1:
      '64': XXX
Conditions:
  WebAccess: !Or
    - !Equals
      - !Ref PyramidProcess
      - 'Everything'
    - !Equals
      - !Ref PyramidProcess
      - 'WebServerAndRouter'
    - !Equals
      - !Ref PyramidProcess
      - 'WebServer'

Resources:
  LaunchInstance:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: https://pyramid-cloudformation.s3.amazonaws.com/marketplace/2020-14/pyramid-single-instance.yaml
      Parameters:
        BaseStackName: !Ref BaseStackName
        AMIID: !FindInMap 
          - AWSAMIRegionMap
          - !Ref 'AWS::Region'
          - '64'
        PyramidProcess: !Ref PyramidProcess
        InstancePurpose: !Ref PyramidProcess
        InstanceType: !Ref InstanceType

        Subnet: !Ref Subnet
        WorkloadSecurityGroups: !Join
          - ','
          - - !Sub '{{resolve:ssm:/Pyramid/${BaseStackName}/PyramidProcessesSecurityGroup:1}}'
            - !Sub '{{resolve:ssm:/Pyramid/${BaseStackName}/MountTargetSecurityGroup:1}}'
            - !If
              - WebAccess
              - !Sub '{{resolve:ssm:/Pyramid/${BaseStackName}/WebAccessSecurityGroup:1}}'
              - !Ref 'AWS::NoValue'
        InstallProxy: !If
          - WebAccess
          - true
          - false
        AssignPublicIP: !If
          - WebAccess
          - true
          - false

        RepositoryType: currentremote
